name: CI

on:
  pull_request:
  push:
    branches:
      - alpha
      - beta
      - main
      - renovate/**

jobs:
  ci-optimization:
    name: CI optimization
    uses: dargmuesli/github-actions/.github/workflows/ci-optimization.yml@e98193e91e9be2af3af784b7a0f25d35bf4eadc5 # 4.0.7
    permissions:
      pull-requests: read
  # release_semantic_dry:
  #   needs: ci-optimization
  #   if: needs.ci-optimization.outputs.continue == 'true'
  #   name: Release (semantic, dry)
  #   uses: dargmuesli/github-actions/.github/workflows/release-semantic.yml@714a68188444d710ffa3e9f35a05f6a9d420931d # 3.2.0
  #   permissions:
  #     contents: write
  #     id-token: write
  #   secrets:
  #     PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
  #   with:
  #     DRY_RUN: true
  build:
    needs: ci-optimization
    if: needs.ci-optimization.outputs.continue == 'true'
    name: Build
    uses: dargmuesli/github-actions/.github/workflows/docker.yml@e98193e91e9be2af3af784b7a0f25d35bf4eadc5 # 4.0.7
  #   needs: release_semantic_dry
    permissions:
      packages: write
    with:
      PUSH: false
  #     BUILD_ARGUMENTS: RELEASE_NAME=${{ needs.release_semantic_dry.outputs.new_release_version }}
  #     TAG: ${{ needs.release_semantic_dry.outputs.new_release_version }}
  # release_semantic:
  #   needs: build
  #   name: Release (semantic)
  #   uses: dargmuesli/github-actions/.github/workflows/release-semantic.yml@714a68188444d710ffa3e9f35a05f6a9d420931d # 3.2.0
  #   permissions:
  #     contents: write
  #     id-token: write
  #   secrets:
  #     PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
